export const ADD_CAPTION = 'ADD_CAPTION';
export const DELETE_CAPTION = 'DELETE_CAPTION';
export const EDIT_CAPTION = 'EDIT_CAPTION';
export const ADD_CAPTIONS = 'ADD_CAPTIONS';
export const CAPTIONS_LOADING = 'CAPTIONS_LOADING';
export const CAPTIONS_FAILED = 'CAPTIONS_FAILED';
