export const PACKAGES =
    [
        {
        id: 0,
        ids: "0",
        type: 0,
        name: 'First Package sample name',
        description: 'First Package sample description',
        price_monthly: 9.99,
        price_annually: 99.99,
        number_accounts: 1,
        is_default: 0,
        trial_day: 1,
        permission: 'First Package sample permission',
        sort: 1,
        status: 1,
        changed: "05-08-19 1:24:53",
        created: "05-08-19 1:24:53"
        },
        {
        id: 1,
        ids: "1",
        type: 1,
        name: 'Second Package sample name',
        description: 'Second Package sample description',
        price_monthly: 9.99,
        price_annually: 99.99,
        number_accounts: 1,
        is_default: 1,
        trial_day: 1,
        permission: 'Second Package sample permission',
        sort: 0,
        status: 0,
        changed: "05-08-19 1:24:53",
        created: "05-08-19 1:24:53"
        },
        {
        id: 2,
        ids: "2",
        type: 2,
        name: 'Third Package sample name',
        description: 'Third Package sample description',
        price_monthly: 9.99,
        price_annually: 99.99,
        number_accounts: 3,
        is_default: 0,
        trial_day: 2,
        permission: 'Third Package sample permission',
        sort: 1,
        status: 0,
        changed: "05-08-19 1:24:53",
        created: "05-08-19 1:24:53"
        },
    ];
