export const USERS =
    [
        {
        id: 0,
        ids: "0",
        admin: 0,
        login_type: 'First Login Type',
        fullname: 'Sample First User fullname',
        email: "user@1.com",
        password: "firstpassword",
        package: 0,
        expiration_date: 'Mon Aug 05 2019 08:43:06 GMT-0500',
        timezone: "GMT-0500",
        permission: "Sample permission",
        settings: "Sample settings for first user",
        activation_key: "First user activation key",
        reset_key: "First user reset key",
        history_ip: "208.108.120.58",
        status: 0,
        changed: "05-08-19 1:24:53",
        created: "05-08-19 1:24:53"
        },
        {
        id: 1,
        ids: "1",
        admin: 0,
        login_type: 'Second Login Type',
        fullname: 'Sample Second User fullname',
        email: "user@2.com",
        password: "secondpassword",
        package: 0,
        expiration_date: 'Mon Aug 05 2019 08:43:06 GMT-0500',
        timezone: "GMT-0500",
        permission: "Sample permission",
        settings: "Sample settings for second user",
        activation_key: "Second user activation key",
        reset_key: "Second user reset key",
        history_ip: "108.108.120.58",
        status: 0,
        changed: "05-08-19 1:24:53",
        created: "05-08-19 1:24:53"
        },
        {
        id: 2,
        ids: "2",
        admin: 0,
        login_type: 'Third Login Type',
        fullname: 'Sample Third User fullname',
        email: "user@3.com",
        password: "thirdpassword",
        package: 0,
        expiration_date: 'Mon Aug 05 2019 08:43:06 GMT-0500',
        timezone: "GMT-0500",
        permission: "Sample permission",
        settings: "Sample settings for Third user",
        activation_key: "Third user activation key",
        reset_key: "Third user reset key",
        history_ip: "208.208.120.58",
        status: 0,
        changed: "05-08-19 1:24:53",
        created: "05-08-19 1:24:53"
        },
    ];
