export const EMAIL_POSTS =
    [
        {
        id: 0,
        ids: "0",
        uid: 12805816332,
        from: "1@email.com",
        to: "recipient1@email.com",
        subject: "Sample Email Subject",
        content: "Sample content first email",
        hasAttachment: 0,
        forwardTo: "Sample Recipient",
        created:'Mon Aug 05 2019 08:43:06 GMT-0500',
        },
        {
        id: 0,
        ids: "0",
        uid: 12805816332,
        from: "2@email.com",
        to: "recipient2@email.com",
        subject: "Sample Email Subject",
        content: "Sample content second email",
        hasAttachment: 1,
        forwardTo: "Sample Recipient",
        created:'Mon Aug 05 2019 08:43:06 GMT-0500',
        },
        {
        id: 0,
        ids: "0",
        uid: 12805816332,
        from: "3@email.com",
        to: "recipient3@email.com",
        subject: "Sample Email Subject",
        content: "Sample content third email",
        hasAttachment: 0,
        forwardTo: "Sample Recipient",
        created:'Mon Aug 05 2019 08:43:06 GMT-0500',
        },
]
